name: Docker Image CI

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Environment Variables Action
      uses: FranzDiebold/github-env-vars-action@v2.1.0
    
    - uses: actions/checkout@v2
      name: Build the Docker image
      run: make build VERSION=$GITHUB_REF
